import type { Metadata } from "next";
import { AppBar, Toolbar } from "@mui/material";
import { ReactNode } from "react";
import Navigation from "./Navigation";
import Footer from "./Footer";
import "./globals.css"; // Import global styles

interface LayoutProps {
  children: ReactNode;
}
export const metadata: Metadata = {
  title: "Ronan Murphy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg", // You can add other formats like .png if needed
    // icon: '/favicon.png',
  },
};
export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="animate-fade-down myNavbar">
            <Navigation />
          </nav>
        </header>

        {children}
        <Footer />
      </body>
    </html>
  );
}
